spring:
  config:
    activate:
      on-profile: "local"
  data:
    mongodb:
      database: summary
      auto-index-creation: true
      authentication-database: admin
      username: rootuser
      password: rootpass
      port: 27017
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    event-queue-name: training-event-queue
