spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update

  activemq:
    broker-url: "tcp://localhost:61616"
logging:
  level:
    web: debug
