spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mariadb://localhost:5432/gym
    username: root
    password: root
  jooq:
    sql-dialect: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  activemq:
    broker-url: "tcp://aws-ec2-url:7034"