spring:
  application:
    name: gym-service
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update

token:
  signing:
    key: ${JWT_SIGNATURE_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

management:
  endpoints:
    web:
      exposure:
        include:
          [ "health", "prometheus" ]
  endpoint:
    health:
      show-details: always



---
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: jdbc:h2:mem:gym-club
    username: test
    password: test
  jooq:
    sql-dialect: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop

token:
  signing:
    key: ${JWT_SIGNATURE_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mariadb://localhost:5432/gym
    username: root
    password: root
  jooq:
    sql-dialect: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

management:
  endpoints:
    web:
      exposure:
        include:
          [ "health", "prometheus" ]
  endpoint:
    health:
      show-details: always

token:
  signing:
    key: ${JWT_SIGNATURE_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true