spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: jdbc:h2:mem:gym-club
    username: test
    password: test
  jooq:
    sql-dialect: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  activemq:
    broker-url: "tcp://localhost:1202"